on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: setup-docker
      uses: docker-practice/actions-setup-docker@1.0.8
      
    - uses: actions/checkout@v2

    - name: Install deps
      run: go mod download
      
    - name: Get fyne-cross
      run: go get github.com/fyne-io/fyne-cross 
      
    - name: Cross Compile Windows
      run: go run github.com/fyne-io/fyne-cross windows -arch=amd64,386
      
    - name: Cross Compile Mac
      run: go run github.com/fyne-io/fyne-cross darwin -arch=*
      
    - name: Cross Compile Linux
      run: go run github.com/fyne-io/fyne-cross darwin -arch=*

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        draft: true
        files: |
          LICENSE.txt
          **/*.zip
